---
title: "data-visualization"
format: html
editor: visual
---

```{r}
library(readr)
library(dplyr)
library(tidyr)
library(forcats) # makes working with factors easier
library(ggplot2)
library(leaflet) # interactive maps
library(DT) # interactive tables
library(scales) # scale functions for visualization
library(janitor) # expedite cleaning and exploring data
library(viridis) # colorblind friendly color pallet
```
```{r}
delta_visits <- read_csv("https://portal.edirepository.org/nis/dataviewer?packageid=edi.587.1&entityid=cda8c1384af0089b506d51ad8507641f") %>% 
    janitor::clean_names() ## Introducing this new package!
```

## Exploring

```{r}
glimpse(delta_visits) #gives a sneaky peal of the data

range(delta_visits$date) #see the range for that column

unique(delta_visits$time_of_day) #prints out the unique values in this column
```


## Getting data ready

```{r}
visits_long<- delta_visits %>% 
  pivot_longer(cols = c("sm_boat", "med_boat", "lrg_boat", "bank_angler", "scientist", "cars"),
               names_to = "vistor_type",
               values_to = "quantity") %>% 
  rename(restore_loc = eco_restore_approximate_location) %>% 
  select(-notes)


#this turns your data frame from wide format to long

```

## Plotting with 'ggplot2'

```{r}

ggplot(visits_long,
       aes(x = restore_loc, y = quantity)) +
  geom_col()

```

## Calculating daily visits by visit type

```{r}

daily_visits<- visits_long %>% 
  group_by(restore_loc, date, vistor_type) %>% 
  summarise(daily_visits = sum(quantity))


```



